name: Elfldr Autobuilds

on: [ push, pull_request, workflow_dispatch ]
  #  push:
  #    branches: [ master ]
  #  pull_request:
  #    branches: [ master ]
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # This techinically also "Installs" it too.
      # TODO: CACHE THIS SO I DON'T KEEP HITTING GITHUB SERVERS.
      - name: Fetch and setup ps2sdk
        run: |
          export PS2DEV=$HOME/ps2dev
          export PS2SDK=$PS2DEV/ps2sdk
          export GSKIT=$PS2DEV/gsKit
          wget -q https://github.com/ps2dev/ps2dev/releases/download/latest/ps2dev-ubuntu-latest.tar.gz
          tar xf ps2dev-ubuntu-latest.tar.gz -C $HOME
          echo $PS2DEV/bin >> $GITHUB_PATH
          echo $PS2DEV/ee/bin >> $GITHUB_PATH
          echo $PS2DEV/iop/bin >> $GITHUB_PATH
          echo $PS2DEV/dvp/bin >> $GITHUB_PATH
          echo $PS2SDK/bin >> $GITHUB_PATH
          echo "PS2DEV=$PS2DEV" >> $GITHUB_ENV
          echo "PS2SDK=$PS2SDK" >> $GITHUB_ENV
          echo "GSKIT=$GSKIT" >> $GITHUB_ENV

      # NOTE: build matrix (better)
      # - Do packaging a bit better (I'm considering using cmake install stuff,
      #   as it's meant for this sorta workflow)
      - name: Build elfldr (release + debug) and package
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchain/ps2.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          cmake -B build_dev -DCMAKE_TOOLCHAIN_FILE=cmake/Toolchain/ps2.cmake -DCMAKE_BUILD_TYPE=Debug
          cmake --build build_dev
          mkdir out
          cp ${{github.workspace}}/build/elfldr.elf out/elfldr_release.elf
          cp ${{github.workspace}}/build_dev/elfldr.elf out/elfldr_release.elf
          cd out
          zip -9 ${{github.workspace}}/elfldr_nightly.zip *

      - name: Upload to Nightly Release
        uses: svenstaro/upload-release-action@2.2.1
        id: uploadrelease
        with:
          asset_name: elfldr_nightly.zip
          release_name: SSX-Elfldr Nightlies
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ${{github.workspace}}/elfldr_nightly.zip
          tag: ${{github.ref}}
          overwrite: true
          prerelease: true
          body: "This is a nightly build of SSX-Elfldr. It may break your windows, kick your cat out, and/or order 20 pizzas for you. If in doubt, please use a stable release or a release I have \"formally\" tested."